# Generated by Django 4.1 on 2022-08-16 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_like_comment_post_comments_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="commenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.profile"
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="liker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.profile"
            ),
        ),
    ]
