# Generated by Django 4.1 on 2022-08-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_comment_commenter_alter_like_liker"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="comments",),
        migrations.RemoveField(model_name="post", name="likes",),
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(blank=True, null=True, to="base.comment"),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(blank=True, null=True, to="base.like"),
        ),
    ]
