# Generated by Django 4.1 on 2022-08-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_remove_post_comments_remove_post_likes_post_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(to="base.comment"),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(to="base.like"),
        ),
    ]
