# Generated by Django 4.1 on 2022-08-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_post_comments_alter_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
