# Generated by Django 4.1 on 2022-08-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_profile_followers_profile_following"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="followers",),
        migrations.RemoveField(model_name="profile", name="following",),
        migrations.AddField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                related_name="my_followers", to="base.profile"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(related_name="follow_to", to="base.profile"),
        ),
    ]
