# Generated by Django 4.1 on 2022-08-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="body",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
