# Generated by Django 4.1 on 2022-08-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_message_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="mark_as_read",
            field=models.BooleanField(default=False),
        ),
    ]
